@startuml
Transaction -> TransactionImpl: commit
TransactionImpl -> DefaultFlushEventListener: onFlush
DefaultFlushEventListener -> AbstractEntityPersister: findDirty(Object[] currentState, Object[] previousState)
@enduml